# Generated by Django 2.1.5 on 2019-02-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0011_t_acct_rootid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_acct',
            name='rootid',
            field=models.IntegerField(),
        ),
    ]
