# Generated by Django 2.1.5 on 2019-02-23 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0012_auto_20190223_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_acct',
            name='rootid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
