# Generated by Django 2.1.5 on 2019-02-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0013_auto_20190223_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='t_acct',
            name='lname',
        ),
    ]
