# Generated by Django 2.1.5 on 2019-02-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0016_auto_20190223_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='baptised',
            field=models.CharField(blank=True, default='Yes', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default='2019-01-01', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='member_status',
            field=models.CharField(blank=True, default='Church Member', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_in_ministry',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='media', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zone',
            field=models.CharField(blank=True, default='IOC', max_length=120, null=True),
        ),
    ]
