# Generated by Django 2.1.5 on 2019-02-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0017_auto_20190225_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
