# Generated by Django 2.1.5 on 2019-02-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0019_auto_20190225_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='access_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
