# Generated by Django 2.1.5 on 2019-02-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0021_auto_20190225_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated',
        ),
    ]
