# Generated by Django 2.1.5 on 2019-02-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0022_auto_20190228_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
