# Generated by Django 2.1.5 on 2019-04-02 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joins', '0025_auto_20190402_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tracker',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
