# Generated by Django 2.1.5 on 2019-04-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0026_userprofile_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='years_in_ministry',
        ),
    ]
