# Generated by Django 2.1.5 on 2019-05-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0027_remove_userprofile_years_in_ministry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='zone',
            new_name='church',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='part_you_enjoyed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='recomendations',
        ),
    ]
