# Generated by Django 2.1.5 on 2019-05-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0028_auto_20190523_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='church',
            field=models.CharField(blank=True, default='Heartfelt International Ministries', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='member_status',
            field=models.CharField(blank=True, default='Student', max_length=20, null=True),
        ),
    ]
