# Generated by Django 2.1.5 on 2019-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0029_auto_20190523_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.CharField(blank=True, default='Student', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program_type',
            field=models.CharField(blank=True, default='Student', max_length=30, null=True),
        ),
    ]
