# Generated by Django 2.1.5 on 2019-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0031_auto_20190523_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='program',
            field=models.CharField(blank=True, default='Diploma in Theology', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='program_type',
            field=models.CharField(blank=True, default='Diploma', max_length=30, null=True),
        ),
    ]
