# Generated by Django 2.2.10 on 2020-06-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0032_auto_20190523_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tracker',
        ),
        migrations.DeleteModel(
            name='t_acct',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
