# Generated by Django 2.2 on 2019-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0002_auto_20190528_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_discussion',
            name='category',
            field=models.CharField(default='policy', max_length=25),
        ),
    ]
