# Generated by Django 2.2 on 2019-05-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteInfo', '0010_t_dictionary_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_dictionary',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
