# Generated by Django 2.2 on 2019-05-25 21:52

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190513_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_location),
        ),
    ]
