# Generated by Django 2.2 on 2019-06-05 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
